export { default as Banner } from './Banner'
export { default as WhyMe } from './WhyMe'
export { default as Faq } from './Faq'
export { default as Services } from './Services'
export { default as Contact } from './Contact'